// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftahgsubczfajcqvtxoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0YWhnc3ViY3pmYWpjcXZ0eG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDQ2ODgsImV4cCI6MjA2ODQ4MDY4OH0.W-tVa3vddBR-_IvqGAfA6kg5EYskjMh5AwYwwgFYIw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});